IMPORTING THE DATASET

In [1]:
import pandas as pd

# Corrected file path string and placement of '.csv'
df = pd.read_csv(r'C:\Users\sruja\Downloads\DAV_ASSIGNMENT-189\deepseek_vs_chatgpt_table.csv')

print("DataSet info: ")
df.info()


DataSet info: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Date                           10000 non-null  object 
 1   Month_Num                      10000 non-null  int64  
 2   Weekday                        10000 non-null  object 
 3   AI_Platform                    10000 non-null  object 
 4   AI_Model_Version               10000 non-null  object 
 5   Active_Users                   10000 non-null  int64  
 6   New_Users                      10000 non-null  int64  
 7   Churned_Users                  10000 non-null  int64  
 8   Daily_Churn_Rate               10000 non-null  float64
 9   Retention_Rate                 10000 non-null  float64
 10  User_ID                        10000 non-null  object 
 11  Query_Type                     10000 non-null  object 
 12  Input_Text                     1

## PERFORMING OPERATIONS -- 

### NUMPY OPERATIONS:
1. Creating arrays
2. Array indexing and slicing
3. Reshaping arrays
4. Concatenation and splitting
5. Universal Functions (Ufuncs)
6. Aggregations
7. Broadcasting
8. Boolean Masks and Fancy Indexing
9. Sorting 
10. Structured arrays

In [8]:
import numpy as np

attack_array = np.array(df["New_Users"])
hp_array = np.array(df["Active_Users"])
speed_array = np.array(df["Churned_Users"])

# Add these lines to see output
print("New Users (attack_array):", attack_array)
print("Active Users (hp_array):", hp_array)
print("Churned Users (speed_array):", speed_array)


New Users (attack_array): [ 25000  25000  25000 ... 170000 170000 170000]
Active Users (hp_array): [ 500000  500000  500000 ... 1700000 1700000 1700000]
Churned Users (speed_array): [25000 25000 25000 ... 34000 34000 34000]


In [9]:
# First 10 values
print(hp_array[:10])
print(attack_array[-5:])

[ 500000  500000  500000  500000 1700000 1700000 1700000 1700000 1700000
 1700000]
[170000 170000 170000 170000 170000]


In [10]:
# Reshape HP
print(hp_array[:20].reshape(4, 5))


[[ 500000  500000  500000  500000 1700000]
 [1700000 1700000 1700000 1700000 1700000]
 [1700000 1700000 1700000 1700000 1700000]
 [1700000  350000  350000  350000 2750000]]


In [11]:
# Concatenation and splitting
concat_array = np.concatenate((hp_array[:10], attack_array[:10]))
split_hp = np.split(hp_array[:10], 2)
print(concat_array)
print(split_hp)


[ 500000  500000  500000  500000 1700000 1700000 1700000 1700000 1700000
 1700000   25000   25000   25000   25000  170000  170000  170000  170000
  170000  170000]
[array([ 500000,  500000,  500000,  500000, 1700000]), array([1700000, 1700000, 1700000, 1700000, 1700000])]


In [12]:
print("Square root:\n", np.sqrt(attack_array))
print("\nMultiplication:\n", np.multiply(attack_array, 2))
print("\nDivision:\n", np.divide(speed_array, 2))
print("\nExponential:\n", np.exp(hp_array))  # Warning: may overflow!
print("\nLogarithm:\n", np.log(attack_array + 1))
print("\nSine of speed:\n", np.sin(np.radians(speed_array)))
print("\nCosine of attack:\n", np.cos(np.radians(attack_array)))
print("\nAbsolute HP:\n", np.abs(hp_array))
print("\nRounded attack:\n", np.round(attack_array))
print("\nHP > 300:\n", np.greater(hp_array, 300))
print("\nHP < 100:\n", np.less(hp_array, 100))
print("\nSpeed == 50:\n", np.equal(speed_array, 50))



Square root:
 [158.11388301 158.11388301 158.11388301 ... 412.31056256 412.31056256
 412.31056256]

Multiplication:
 [ 50000  50000  50000 ... 340000 340000 340000]

Division:
 [12500. 12500. 12500. ... 17000. 17000. 17000.]

Exponential:
 [inf inf inf ... inf inf inf]

Logarithm:
 [10.1266711 10.1266711 10.1266711 ... 12.0435596 12.0435596 12.0435596]

Sine of speed:
 [0.34202014 0.34202014 0.34202014 ... 0.34202014 0.34202014 0.34202014]

Cosine of attack:
 [-0.93969262 -0.93969262 -0.93969262 ...  0.17364818  0.17364818
  0.17364818]

Absolute HP:
 [ 500000  500000  500000 ... 1700000 1700000 1700000]

Rounded attack:
 [ 25000  25000  25000 ... 170000 170000 170000]

HP > 300:
 [ True  True  True ...  True  True  True]

HP < 100:
 [False False False ... False False False]

Speed == 50:
 [False False False ... False False False]


C:\Users\sruja\AppData\Local\Temp\ipykernel_29104\9784098.py:4: RuntimeWarning: overflow encountered in exp
  print("\nExponential:\n", np.exp(hp_array))  # Warning: may overflow!


In [13]:
# Aggregations
print("Total HP:", np.sum(hp_array))
print("Mean Attack:", np.mean(attack_array))
print("Median Speed:", np.median(speed_array))
print("Std HP:", np.std(hp_array))
print("Variance Attack:", np.var(attack_array))
print("Min Speed:", np.min(speed_array))
print("Max Speed:", np.max(speed_array))
print("Cumulative HP Sum:", np.cumsum(hp_array))




Total HP: 11962550000
Mean Attack: 100508.75
Median Speed: 35000.0
Std HP: 744409.3127943793
Variance Attack: 7323901798.4375
Min Speed: 4000
Max Speed: 61000
Cumulative HP Sum: [     500000     1000000     1500000 ... 11959150000 11960850000
 11962550000]


In [14]:
# Sort and ranking
df_sorted_speed = df.sort_values("Churned_Users", ascending=False)
print(df_sorted_speed.head())


            Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
5783  2025-02-01          2  Saturday    DeepSeek  DeepSeek-Chat 1.5   
4478  2023-07-28          7    Friday     ChatGPT        GPT-4-turbo   
4538  2023-07-14          7    Friday     ChatGPT        GPT-4-turbo   
4537  2023-07-14          7    Friday     ChatGPT        GPT-4-turbo   
4535  2023-07-14          7    Friday     ChatGPT        GPT-4-turbo   

      Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  \
5783       3050000     305000          61000              0.02   
4478       1200000      60000          60000              0.05   
4538       1200000      60000          60000              0.05   
4537       1200000      60000          60000              0.05   
4535       1200000      60000          60000              0.05   

      Retention_Rate  ... Session_Duration_sec     Device_Type Language  \
5783            0.95  ...                   60          Mobile       de   
4478            0.95

In [15]:
sorted_indices = np.argsort(attack_array)
top_5_fastest = np.partition(speed_array, -5)[-5:]
print("Top 5 fastest churn:", top_5_fastest)


Top 5 fastest churn: [60000 60000 60000 60000 61000]


In [16]:

# Broadcasting
attack_array += 5
print(attack_array)

[ 25005  25005  25005 ... 170005 170005 170005]


In [17]:
# Boolean Masking
high_hp = df[df["Active_Users"] > 100000]
print(high_hp.head())

         Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
0  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
1  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
2  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
3  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
4  2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   

   Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  Retention_Rate  \
0        500000      25005          25000              0.05            0.95   
1        500000      25005          25000              0.05            0.95   
2        500000      25005          25000              0.05            0.95   
3        500000      25005          25000              0.05            0.95   
4       1700000     170005          34000              0.02            0.95   

   ... Session_Duration_sec     Device_Type Language  Response_Accuracy  \
0  ...                   40        

In [18]:
# Fancy Indexing
print(df.iloc[[0, 5, 10]])

          Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
0   2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
5   2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   
10  2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   

    Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  Retention_Rate  \
0         500000      25005          25000              0.05            0.95   
5        1700000     170005          34000              0.02            0.95   
10       1700000     170005          34000              0.02            0.95   

    ... Session_Duration_sec Device_Type Language  Response_Accuracy  \
0   ...                   40      Mobile       es             0.7842   
5   ...                   18      Mobile       de             0.8992   
10  ...                   20      Mobile       es             0.8947   

    Response_Speed_sec Response_Time_Category  Correction_Needed  \
0                 3.30               Stan

In [21]:
import numpy as np

structured_array = np.array(
    list(zip(df["User_ID"], df["AI_Platform"], df["Active_Users"])),
    dtype=[("ID", "U50"), ("Platform", "U20"), ("HP", "i4")]
)

print(structured_array[:5])

[('c878a177-2da9-4224-8cf8-1d56a1c6a755', 'ChatGPT',  500000)
 ('7096d0f1-d0dc-4333-a5d0-de9dfd1b99fa', 'ChatGPT',  500000)
 ('e690c254-582f-49c1-89c3-0b4dd8ee59be', 'ChatGPT',  500000)
 ('0b6a010d-9d03-44c4-bf7f-7f8d2cc461e2', 'ChatGPT',  500000)
 ('ffa90616-1fa9-48ff-842d-e84e193c64f4', 'DeepSeek', 1700000)]


## Pandas Operations: 
1. Pandas Series
2. Pandas DataFrame
3. Indexing and Selecting
4. Index Alignment and Operations
5. Handling Missing data
6. Heirarchial Indexing 

In [22]:

# Convert HP column to Series
hp_series = pd.Series(df["Active_Users"])
print(hp_series.head())



0     500000
1     500000
2     500000
3     500000
4    1700000
Name: Active_Users, dtype: int64


In [ ]:

# Arithmetic
df["attack_boosted"] = df["New_Users"] + 10
df["speed_halved"] = df["Churned_Users"] / 2


In [ ]:
# operations on series
print(df["attack"].sum())  # Total Attack
print(df["speed"].mean())  # Average Speed
print(df["hp"].min())      # Minimum HP
print(df["defense"].max()) # Maximum Defense
print(df["type"].value_counts())  # Count pokemon per Type


In [ ]:
# Apply function
df["attack_modified"] = df["New_Users"].apply(lambda x: x * 1.2 if x > 100000 else x)


In [29]:
print(df["New_Users"].sum())
print(df["Churned_Users"].mean())
print(df["Active_Users"].min())
print(df["Retention_Rate"].max())
print(df["AI_Platform"].value_counts())


1005137500
35395.15
200000
0.95
AI_Platform
ChatGPT     5076
DeepSeek    4924
Name: count, dtype: int64


In [30]:

# Sorting and Ranking
df["speed_rank"] = df["Churned_Users"].rank(method="min", ascending=False)
print(df["speed_rank"].head())

0    7049.0
1    7049.0
2    7049.0
3    7049.0
4    5184.0
Name: speed_rank, dtype: float64


In [ ]:
# Fill missing values
df.update(df[["New_Users"]].fillna(df["New_Users"].mean()))
df.dropna(subset=["Churned_Users"], inplace=True)


In [ ]:
# Create a new column (Total Stats)
df["total_stats"] = df["attack"] + df["defense"] + df["speed"] + df["hp"]

# Multiply entire DataFrame by 2 (only numeric columns)
df_numeric = df.select_dtypes(include="number")
df_doubled = df_numeric * 2
print(df_numeric, df_doubled)


In [ ]:
# Group pokemon by Type and get Average Attack
type_attack = df.groupby("type")["attack"].mean()
print(type_attack)

# Get Maximum Speed per Type
type_speed = df.groupby("type")["speed"].max()
print(type_speed)

In [ ]:
# Sort pokemon by Attack (Descending)
df_sorted = df.sort_values(by="attack", ascending=False)
print(df_sorted)
# Sort by Multiple Columns (Sort by Attack, then Speed)
df_sorted = df.sort_values(by=["attack", "speed"], ascending=[False, True])
print(df_sorted)

In [ ]:
# Apply a function to an entire column
df["speed_modified"] = df["speed"].apply(lambda x: x * 1.5 if x > 80 else x)

# Apply function to multiple columns (Row-wise)
df["power_score"] = df.apply(lambda row: row["attack"] + row["speed"], axis=1)
print(df["speed_modified"])
print(df["power_score"])


In [ ]:
# Checking for missing values
print("\n Missing Values in Dataset:")
print(df.isnull().sum())

# Filling missing Attack values with Mean
df["attack"] = df["attack"].fillna(df["attack"].mean())
print("\n Filling Missing Attack Values with Mean:")
print(df[["name", "attack"]].head())


In [ ]:
# Creating extra DataFrame for merging
extra_data = pd.DataFrame({
    "name": df["name"].head(),  # Take first few pokemon names
    "legendary": [False, False, True, False, True]  # Random legendary status
})

# Merging on 'name' column
df_merged = df.merge(extra_data, on="name", how="left")
print("\n🔹 Merging with Extra Data (Legendary Status):")
print(df_merged.head())


# Combining Datasets: 
1. Concatenation
2. Merging
3. Joins
4. Aggregation and Grouping
5. Pivot Tables


In [ ]:
import pandas as pd
# Concatenation: 
# Create a small dataset with new pokemon
new_pokemon = pd.DataFrame({
    "name": ["Newpokemon1", "NewPokemon2"],
    "type_1": ["Electric", "Grass"],
    "hp": [35, 45],
    "attack": [55, 49]
})

# Concatenate vertically (Adding rows)
df_combined = pd.concat([df, new_pokemon], ignore_index=True)
print(df_combined.tail())


In [ ]:
#Merging: 
# Example evolution dataset
evolution_data = pd.DataFrame({
    "name": ["Bulbasaur", "Charmander", "Squirtle"],
    "evolves_to": ["Ivysaur", "Charmeleon", "Wartortle"]
})

# Merge on "name" column (Default: INNER JOIN)
df_merged = pd.merge(df, evolution_data, on="name", how="left")
print(df_merged.head())


In [ ]:
import pandas as pd
# Joins: 
# pokemon stats dataset
df_stats = pd.DataFrame({
    "hp": [45, 60, 80],
    "attack": [49, 62, 82],
    "defense": [49, 63, 83]
}, index=["Bulbasaur", "Charmeleon", "Venusaur"])

# pokemon types dataset
df_types = pd.DataFrame({
    "type_1": ["Grass", "Fire", "Grass"],
    "type_2": ["Poison", None, "Poison"]
}, index=["Bulbasaur", "Charmeleon", "Venusaur"])

# Perform the join
df_joined = df_stats.join(df_types)
print("\n",df_joined)

# INNER JOIN (Only matching pokemon)
df_inner = df_stats.join(df_types, how="inner")
print("\n",df_inner)

# OUTER JOIN (Keeps all pokemon, fills missing values with NaN)
df_outer = df_stats.join(df_types, how="outer")
print("\n",df_outer)

# RIGHT JOIN (Keeps all pokemon from df_types)
df_right = df_stats.join(df_types, how="right")
print("\n",df_right)

In [ ]:
import pandas as pd

# Aggregating pokemon stats
print("Total HP:", df["hp"].sum())      # Sum of all HPs
print("Average Attack:", df["attack"].mean())  # Mean attack
print("Strongest pokemon (Attack):", df["attack"].max())  # Max attack
print("Weakest pokemon (Defense):", df["defense"].min())  # Min defense
print("Total pokemon:", df["name"].count())  # Total count


In [ ]:
# Group-By: 
# Group pokemon by Type and Get Stats
type_stats = df.groupby("name")[["attack", "hp", "defense"]].agg(["min", "max", "mean"])
print("\n",type_stats)


In [ ]:
#GroupBy - Count pokemon per Group
type_counts = df.groupby("attack")["name"].count()
print("\n",type_counts)


In [ ]:
#GroupBy - Find the Strongest pokemon per Type
strongest_per_type = df.loc[df.groupby("type")["attack"].idxmax(), ["name", "attack"]]
print(strongest_per_type)


In [ ]:
#GroupBy - Average HP per type
print(df.groupby("type")["hp"].mean())

In [ ]:
#Pivot tables:
#Average Attack per pokemon Type
pivot_table = df.pivot_table(values="attack", index="type", aggfunc="mean")
print(pivot_table)


In [ ]:
# Pivot Table with Multiple Aggregations (Min, Max, Mean Attack)
pivot_table = df.pivot_table(values="attack", index="type", aggfunc=["min", "max", "mean"])
print(pivot_table)


In [ ]:
#Counting pokemon per Type (Using Pivot Table)
pivot_table = df.pivot_table(values="name", index="type", aggfunc="count")
print(pivot_table)
