IMPORTING THE DATASET

In [1]:
import pandas as pd

# Corrected file path string and placement of '.csv'
df = pd.read_csv(r'C:\Users\sruja\Downloads\DAV_ASSIGNMENT-189\deepseek_vs_chatgpt_table.csv')

print("DataSet info: ")
df.info()


DataSet info: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Date                           10000 non-null  object 
 1   Month_Num                      10000 non-null  int64  
 2   Weekday                        10000 non-null  object 
 3   AI_Platform                    10000 non-null  object 
 4   AI_Model_Version               10000 non-null  object 
 5   Active_Users                   10000 non-null  int64  
 6   New_Users                      10000 non-null  int64  
 7   Churned_Users                  10000 non-null  int64  
 8   Daily_Churn_Rate               10000 non-null  float64
 9   Retention_Rate                 10000 non-null  float64
 10  User_ID                        10000 non-null  object 
 11  Query_Type                     10000 non-null  object 
 12  Input_Text                     1

## PERFORMING OPERATIONS -- 

### NUMPY OPERATIONS:
1. Creating arrays
2. Array indexing and slicing
3. Reshaping arrays
4. Concatenation and splitting
5. Universal Functions (Ufuncs)
6. Aggregations
7. Broadcasting
8. Boolean Masks and Fancy Indexing
9. Sorting 
10. Structured arrays

In [2]:
import numpy as np

attack_array = np.array(df["New_Users"])
hp_array = np.array(df["Active_Users"])
speed_array = np.array(df["Churned_Users"])

# Add these lines to see output
print("New Users (attack_array):", attack_array)
print("Active Users (hp_array):", hp_array)
print("Churned Users (speed_array):", speed_array)


New Users (attack_array): [ 25000  25000  25000 ... 170000 170000 170000]
Active Users (hp_array): [ 500000  500000  500000 ... 1700000 1700000 1700000]
Churned Users (speed_array): [25000 25000 25000 ... 34000 34000 34000]


In [3]:
# First 10 values
print(hp_array[:10])
print(attack_array[-5:])

[ 500000  500000  500000  500000 1700000 1700000 1700000 1700000 1700000
 1700000]
[170000 170000 170000 170000 170000]


In [4]:
# Reshape HP
print(hp_array[:20].reshape(4, 5))


[[ 500000  500000  500000  500000 1700000]
 [1700000 1700000 1700000 1700000 1700000]
 [1700000 1700000 1700000 1700000 1700000]
 [1700000  350000  350000  350000 2750000]]


In [5]:
# Concatenation and splitting
concat_array = np.concatenate((hp_array[:10], attack_array[:10]))
split_hp = np.split(hp_array[:10], 2)
print(concat_array)
print(split_hp)


[ 500000  500000  500000  500000 1700000 1700000 1700000 1700000 1700000
 1700000   25000   25000   25000   25000  170000  170000  170000  170000
  170000  170000]
[array([ 500000,  500000,  500000,  500000, 1700000]), array([1700000, 1700000, 1700000, 1700000, 1700000])]


In [40]:
import numpy as np

# Use these arrays as examples or replace them with your actual arrays
attack_array = np.array([25005, 25005, 25005, 25005, 170005, 170005, 170005, 170005, 170005, 170005])
speed_array = np.array([25000, 25000, 25000, 25000, 34000, 34000, 34000, 34000, 34000, 34000])
hp_array = np.array([500000, 500000, 500000, 500000, 1700000, 1700000, 1700000, 1700000, 1700000, 1700000])

np.set_printoptions(precision=2, suppress=True)

# Display only 10 values explicitly
print("Square root:", np.sqrt(attack_array))
print("Multiplication:", np.multiply(attack_array, 2))
print("Division:", np.divide(speed_array, 2))
print("Exponential:", np.exp(np.clip(hp_array, None, 700)))  # Clip to prevent overflow
print("Logarithm:", np.log(attack_array + 1))
print("Sine of speed:", np.sin(np.radians(speed_array)))
print("Cosine of attack:", np.cos(np.radians(attack_array)))
print("Absolute HP:", np.abs(hp_array))
print("Rounded attack:", np.round(attack_array))
print("HP > 300:", np.greater(hp_array, 300))
print("HP < 100:", np.less(hp_array, 100))
print("Speed == 50:", np.equal(speed_array, 50))




Square root: [158.13 158.13 158.13 158.13 412.32 412.32 412.32 412.32 412.32 412.32]
Multiplication: [ 50010  50010  50010  50010 340010 340010 340010 340010 340010 340010]
Division: [12500. 12500. 12500. 12500. 17000. 17000. 17000. 17000. 17000. 17000.]
Exponential: [1.01e+304 1.01e+304 1.01e+304 1.01e+304 1.01e+304 1.01e+304 1.01e+304 1.01e+304 1.01e+304 1.01e+304]
Logarithm: [10.13 10.13 10.13 10.13 12.04 12.04 12.04 12.04 12.04 12.04]
Sine of speed: [0.34 0.34 0.34 0.34 0.34 0.34 0.34 0.34 0.34 0.34]
Cosine of attack: [-0.97 -0.97 -0.97 -0.97  0.09  0.09  0.09  0.09  0.09  0.09]
Absolute HP: [ 500000  500000  500000  500000 1700000 1700000 1700000 1700000 1700000 1700000]
Rounded attack: [ 25005  25005  25005  25005 170005 170005 170005 170005 170005 170005]
HP > 300: [ True  True  True  True  True  True  True  True  True  True]
HP < 100: [False False False False False False False False False False]
Speed == 50: [False False False False False False False False False False]


In [7]:
# Aggregations
print("Total HP:", np.sum(hp_array))
print("Mean Attack:", np.mean(attack_array))
print("Median Speed:", np.median(speed_array))
print("Std HP:", np.std(hp_array))
print("Variance Attack:", np.var(attack_array))
print("Min Speed:", np.min(speed_array))
print("Max Speed:", np.max(speed_array))
print("Cumulative HP Sum:", np.cumsum(hp_array))




Total HP: 11962550000
Mean Attack: 100508.75
Median Speed: 35000.0
Std HP: 744409.3127943793
Variance Attack: 7323901798.4375
Min Speed: 4000
Max Speed: 61000
Cumulative HP Sum: [     500000     1000000     1500000 ... 11959150000 11960850000
 11962550000]


In [8]:
# Sort and ranking
df_sorted_speed = df.sort_values("Churned_Users", ascending=False)
print(df_sorted_speed.head())


            Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
5783  2025-02-01          2  Saturday    DeepSeek  DeepSeek-Chat 1.5   
4478  2023-07-28          7    Friday     ChatGPT        GPT-4-turbo   
4538  2023-07-14          7    Friday     ChatGPT        GPT-4-turbo   
4537  2023-07-14          7    Friday     ChatGPT        GPT-4-turbo   
4535  2023-07-14          7    Friday     ChatGPT        GPT-4-turbo   

      Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  \
5783       3050000     305000          61000              0.02   
4478       1200000      60000          60000              0.05   
4538       1200000      60000          60000              0.05   
4537       1200000      60000          60000              0.05   
4535       1200000      60000          60000              0.05   

      Retention_Rate  ... Session_Duration_sec     Device_Type Language  \
5783            0.95  ...                   60          Mobile       de   
4478            0.95

In [9]:
sorted_indices = np.argsort(attack_array)
top_5_fastest = np.partition(speed_array, -5)[-5:]
print("Top 5 fastest churn:", top_5_fastest)


Top 5 fastest churn: [60000 60000 60000 60000 61000]


In [10]:

# Broadcasting
attack_array += 5
print(attack_array)

[ 25005  25005  25005 ... 170005 170005 170005]


In [11]:
# Boolean Masking
high_hp = df[df["Active_Users"] > 100000]
print(high_hp.head())

         Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
0  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
1  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
2  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
3  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
4  2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   

   Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  Retention_Rate  \
0        500000      25005          25000              0.05            0.95   
1        500000      25005          25000              0.05            0.95   
2        500000      25005          25000              0.05            0.95   
3        500000      25005          25000              0.05            0.95   
4       1700000     170005          34000              0.02            0.95   

   ... Session_Duration_sec     Device_Type Language  Response_Accuracy  \
0  ...                   40        

In [12]:
# Fancy Indexing
print(df.iloc[[0, 5, 10]])

          Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
0   2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
5   2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   
10  2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   

    Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  Retention_Rate  \
0         500000      25005          25000              0.05            0.95   
5        1700000     170005          34000              0.02            0.95   
10       1700000     170005          34000              0.02            0.95   

    ... Session_Duration_sec Device_Type Language  Response_Accuracy  \
0   ...                   40      Mobile       es             0.7842   
5   ...                   18      Mobile       de             0.8992   
10  ...                   20      Mobile       es             0.8947   

    Response_Speed_sec Response_Time_Category  Correction_Needed  \
0                 3.30               Stan

In [13]:
import numpy as np

structured_array = np.array(
    list(zip(df["User_ID"], df["AI_Platform"], df["Active_Users"])),
    dtype=[("ID", "U50"), ("Platform", "U20"), ("HP", "i4")]
)

print(structured_array[:5])

[('c878a177-2da9-4224-8cf8-1d56a1c6a755', 'ChatGPT',  500000)
 ('7096d0f1-d0dc-4333-a5d0-de9dfd1b99fa', 'ChatGPT',  500000)
 ('e690c254-582f-49c1-89c3-0b4dd8ee59be', 'ChatGPT',  500000)
 ('0b6a010d-9d03-44c4-bf7f-7f8d2cc461e2', 'ChatGPT',  500000)
 ('ffa90616-1fa9-48ff-842d-e84e193c64f4', 'DeepSeek', 1700000)]


## Pandas Operations: 
1. Pandas Series
2. Pandas DataFrame
3. Indexing and Selecting
4. Index Alignment and Operations
5. Handling Missing data
6. Heirarchial Indexing 

In [14]:

# Convert HP column to Series
hp_series = pd.Series(df["Active_Users"])
print(hp_series.head())



0     500000
1     500000
2     500000
3     500000
4    1700000
Name: Active_Users, dtype: int64


In [15]:

# Arithmetic
df["attack_boosted"] = df["New_Users"] + 10
df["speed_halved"] = df["Churned_Users"] / 2


In [17]:
# operations on series
print("Total New Users:", df["New_Users"].sum())            # total attack → total new users
print("Average Churned Users:", df["Churned_Users"].mean()) # avg speed → avg churn
print("Minimum Active Users:", df["Active_Users"].min())     # min hp → min active users
print("Maximum Experience Score:", df["User_Experience_Score"].max())  # max defense
print("\nUser count per AI Platform:\n", df["AI_Platform"].value_counts())  # count per type



Total New Users: 1005137500
Average Churned Users: 35395.15
Minimum Active Users: 200000
Maximum Experience Score: 2.28

User count per AI Platform:
 AI_Platform
ChatGPT     5076
DeepSeek    4924
Name: count, dtype: int64


In [ ]:
# Apply function
df["attack_modified"] = df["New_Users"].apply(lambda x: x * 1.2 if x > 100000 else x)


In [ ]:
print(df["New_Users"].sum())
print(df["Churned_Users"].mean())
print(df["Active_Users"].min())
print(df["Retention_Rate"].max())
print(df["AI_Platform"].value_counts())


1005137500
35395.15
200000
0.95
AI_Platform
ChatGPT     5076
DeepSeek    4924
Name: count, dtype: int64


In [ ]:

# Sorting and Ranking
df["speed_rank"] = df["Churned_Users"].rank(method="min", ascending=False)
print(df["speed_rank"].head())

0    7049.0
1    7049.0
2    7049.0
3    7049.0
4    5184.0
Name: speed_rank, dtype: float64


In [ ]:
# Fill missing values
df.update(df[["New_Users"]].fillna(df["New_Users"].mean()))
df.dropna(subset=["Churned_Users"], inplace=True)


In [ ]:
# DataFrame subset
subset_df = df[["AI_Platform", "AI_Model_Version", "Active_Users"]]
print(subset_df.head())


  AI_Platform   AI_Model_Version  Active_Users
0     ChatGPT        GPT-4-turbo        500000
1     ChatGPT        GPT-4-turbo        500000
2     ChatGPT        GPT-4-turbo        500000
3     ChatGPT        GPT-4-turbo        500000
4    DeepSeek  DeepSeek-Chat 1.5       1700000


In [ ]:
# New column
df["total_stats"] = df["New_Users"] + df["Churned_Users"] + df["Active_Users"]

# Multiply numeric only
df_numeric = df.select_dtypes(include="number")
df_doubled = df_numeric * 2
print(df_doubled.head())

   Month_Num  Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  \
0         18       1000000      50010          50000              0.10   
1         18       1000000      50010          50000              0.10   
2         18       1000000      50010          50000              0.10   
3         18       1000000      50010          50000              0.10   
4         10       3400000     340010          68000              0.04   

   Retention_Rate  Input_Text_Length  Response_Tokens  User_Rating  \
0             1.9                 14              560            8   
1             1.9                 14              160            8   
2             1.9                 16              262            6   
3             1.9                 14              852           10   
4             1.9                 12              430           10   

   User_Experience_Score  ...  Response_Accuracy  Response_Speed_sec  \
0                   2.56  ...             1.5684              

In [ ]:

# Group by and aggregation
type_attack = df.groupby("AI_Platform")["New_Users"].mean()
print(type_attack)

AI_Platform
ChatGPT      37666.052009
DeepSeek    165301.506905
Name: New_Users, dtype: float64


In [ ]:

type_speed = df.groupby("AI_Platform")["Churned_Users"].max()
print(type_speed)


AI_Platform
ChatGPT     60000
DeepSeek    61000
Name: Churned_Users, dtype: int64


In [ ]:

# Sort
df_sorted = df.sort_values(by=["New_Users", "Churned_Users"], ascending=[False, True])
print(df_sorted.head())


            Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
5783  2025-02-01          2  Saturday    DeepSeek  DeepSeek-Chat 1.5   
69    2025-01-12          1    Sunday    DeepSeek  DeepSeek-Chat 1.5   
70    2025-01-12          1    Sunday    DeepSeek  DeepSeek-Chat 1.5   
71    2025-01-12          1    Sunday    DeepSeek  DeepSeek-Chat 1.5   
72    2025-01-12          1    Sunday    DeepSeek  DeepSeek-Chat 1.5   

      Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  \
5783       3050000     305005          61000              0.02   
69         2900000     290005          58000              0.02   
70         2900000     290005          58000              0.02   
71         2900000     290005          58000              0.02   
72         2900000     290005          58000              0.02   

      Retention_Rate  ... Response_Time_Category Correction_Needed  \
5783            0.95  ...                   Fast                 0   
69              0.95  ...     

In [ ]:
# Apply functions
df["speed_modified"] = df["Churned_Users"].apply(lambda x: x * 1.5 if x > 80000 else x)
df["power_score"] = df.apply(lambda row: row["New_Users"] + row["Churned_Users"], axis=1)
print(df[["speed_modified", "power_score"]].head())


   speed_modified  power_score
0           25000        50005
1           25000        50005
2           25000        50005
3           25000        50005
4           34000       204005


In [ ]:
# Check nulls
print("\nMissing values:\n", df.isnull().sum())


Missing values:
 Date                               0
Month_Num                          0
Weekday                            0
AI_Platform                        0
AI_Model_Version                   0
Active_Users                       0
New_Users                          0
Churned_Users                      0
Daily_Churn_Rate                   0
Retention_Rate                     0
User_ID                            0
Query_Type                         0
Input_Text                         0
Input_Text_Length                  0
Response_Tokens                    0
Topic_Category                     0
User_Rating                        0
User_Experience_Score              0
Session_Duration_sec               0
Device_Type                        0
Language                           0
Response_Accuracy                379
Response_Speed_sec                 0
Response_Time_Category             0
Correction_Needed                  0
User_Return_Frequency              0
Customer_Support_Int

In [ ]:
# Fill missing attack (New_Users)
df["New_Users"] = df["New_Users"].fillna(df["New_Users"].mean())
print("\nFilled missing New_Users:\n", df[["AI_Platform", "New_Users"]].head())


Filled missing New_Users:
   AI_Platform  New_Users
0     ChatGPT      25005
1     ChatGPT      25005
2     ChatGPT      25005
3     ChatGPT      25005
4    DeepSeek     170005


# Combining Datasets: 
1. Concatenation
2. Merging
3. Joins
4. Aggregation and Grouping
5. Pivot Tables


In [ ]:
# Concatenation
new_data = pd.DataFrame({
    "AI_Platform": ["NeoBot", "SynthAI"],
    "AI_Model_Version": ["1.0", "2.0"],
    "Active_Users": [100000, 200000],
    "New_Users": [20000, 30000]
})
df_combined = pd.concat([df, new_data], ignore_index=True)
print(df_combined.tail())



             Date  Month_Num Weekday AI_Platform   AI_Model_Version  \
9997   2024-05-17        5.0  Friday    DeepSeek  DeepSeek-Chat 1.5   
9998   2024-05-17        5.0  Friday    DeepSeek  DeepSeek-Chat 1.5   
9999   2024-05-17        5.0  Friday    DeepSeek  DeepSeek-Chat 1.5   
10000         NaN        NaN     NaN      NeoBot                1.0   
10001         NaN        NaN     NaN     SynthAI                2.0   

       Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  \
9997        1700000     170005        34000.0              0.02   
9998        1700000     170005        34000.0              0.02   
9999        1700000     170005        34000.0              0.02   
10000        100000      20000            NaN               NaN   
10001        200000      30000            NaN               NaN   

       Retention_Rate  ... User_Return_Frequency  \
9997             0.95  ...                  10.0   
9998             0.95  ...                   5.0   
9999          

In [ ]:

# Merge example
extra_data = pd.DataFrame({
    "AI_Platform": df["AI_Platform"].head(),
    "legendary": [False, False, True, False, True]
})
df_merged = df.merge(extra_data, on="AI_Platform", how="left")
print("\nMerged Extra Data:\n", df_merged.head())



Merged Extra Data:
          Date  Month_Num   Weekday AI_Platform AI_Model_Version  Active_Users  \
0  2024-09-21          9  Saturday     ChatGPT      GPT-4-turbo        500000   
1  2024-09-21          9  Saturday     ChatGPT      GPT-4-turbo        500000   
2  2024-09-21          9  Saturday     ChatGPT      GPT-4-turbo        500000   
3  2024-09-21          9  Saturday     ChatGPT      GPT-4-turbo        500000   
4  2024-09-21          9  Saturday     ChatGPT      GPT-4-turbo        500000   

   New_Users  Churned_Users  Daily_Churn_Rate  Retention_Rate  ...  \
0      25005          25000              0.05            0.95  ...   
1      25005          25000              0.05            0.95  ...   
2      25005          25000              0.05            0.95  ...   
3      25005          25000              0.05            0.95  ...   
4      25005          25000              0.05            0.95  ...   

  Customer_Support_Interactions                                        

In [ ]:
# Join example
df_stats = pd.DataFrame({
    "Active_Users": [450000, 600000],
    "New_Users": [49000, 62000],
    "Churned_Users": [49000, 63000]
}, index=["NeoBot", "SynthAI"])

df_types = pd.DataFrame({
    "type_1": ["Custom", "Synthetic"],
    "type_2": ["ML", None]
}, index=["NeoBot", "SynthAI"])

df_joined = df_stats.join(df_types)
print("\nJoined Stats and Types:\n", df_joined)


Joined Stats and Types:
          Active_Users  New_Users  Churned_Users     type_1 type_2
NeoBot         450000      49000          49000     Custom     ML
SynthAI        600000      62000          63000  Synthetic   None


In [ ]:
# Group by with multiple agg
type_stats = df.groupby("AI_Platform")[["New_Users", "Active_Users", "Churned_Users"]].agg(["min", "max", "mean"])
print("\nGrouped Stats:\n", type_stats)

type_counts = df.groupby("New_Users")["AI_Platform"].count()
print("\nUser Count per New_Users:\n", type_counts)

strongest = df.loc[df.groupby("AI_Platform")["New_Users"].idxmax(), ["AI_Platform", "New_Users"]]
print("\nStrongest per Platform:\n", strongest)

print("\nAverage HP (Active Users) per Platform:\n", df.groupby("AI_Platform")["Active_Users"].mean())




Grouped Stats:
             New_Users                        Active_Users           \
                  min     max           mean          min      max   
AI_Platform                                                          
ChatGPT         12505   60005   37666.052009       250000  1200000   
DeepSeek        20005  305005  165301.506905       200000  3050000   

                          Churned_Users                       
                     mean           min    max          mean  
AI_Platform                                                   
ChatGPT      7.532210e+05         12500  60000  37661.052009  
DeepSeek     1.652965e+06          4000  61000  33059.301381  

User Count per New_Users:
 New_Users
12505      20
15005     225
17505     240
20005     367
22505     208
25005     251
27505     379
30005     255
32505     422
35005     430
37505     154
40005     285
42505     262
45005     320
47505     312
50005     479
52505     401
55005     243
57505     183
60005     229

In [18]:

# Pivot table
pivot = df.pivot_table(values="New_Users", index="AI_Platform", aggfunc="mean")
print("\nPivot Table (Average New Users):\n", pivot)

pivot_multi = df.pivot_table(values="New_Users", index="AI_Platform", aggfunc=["min", "max", "mean"])
print("\nPivot Table with Multiple Aggs:\n", pivot_multi)

pivot_counts = df.pivot_table(values="User_ID", index="AI_Platform", aggfunc="count")
print("\nCount per Platform:\n", pivot_counts)



Pivot Table (Average New Users):
                  New_Users
AI_Platform               
ChatGPT       37666.052009
DeepSeek     165301.506905

Pivot Table with Multiple Aggs:
                   min       max           mean
            New_Users New_Users      New_Users
AI_Platform                                   
ChatGPT         12505     60005   37666.052009
DeepSeek        20005    305005  165301.506905

Count per Platform:
              User_ID
AI_Platform         
ChatGPT         5076
DeepSeek        4924
